### ISSUE TITLE
String conversion broken in python 3.8.5

### ISSUE THREAD

**Issue by malramsay64** [clbarnes/backports.strenum#1]
I have encountered some unusual behaviour in using this library with python 3.8.5, where the Enum.__str__ method is being used over the str.__str__ method.

See the below for an example demonstrating the failure.

```python3
❯ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from backports.strenum import StrEnum
>>> class Test(StrEnum):
...     value = "value"
...
>>> str(Test.value) == Test.value
False
>>> StrEnum.__str__
<function Enum.__str__ at 0x7f60f0fde5e0>
>>> StrEnum.__str__ = str.__str__
>>> StrEnum.__str__
<slot wrapper '__str__' of 'str' objects>
>>> class Test(StrEnum):
...     value = "value"
...
>>> str(Test.value) == Test.value
True
>>>
```
There are no issues on python 3.8.6 so this is not a huge problem, however thought it should be noted.

What I believe to be the relevant python bug https://bugs.python.org/issue41789

**Comment by clbarnes** [comment]
Thanks very much for reporting this! I've updated the minimum supported version in the README to 3.8.6.
