### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by mgorny** [clbarnes/backports.strenum#12]
`pyproject.toml` specifies the license as `MIT`:

https://github.com/clbarnes/backports.strenum/blob/9cb063cdc2d2e94229e7fc66c9a989379e1bff68/pyproject.toml#L10

However, the LICENSE file is clearly PSF:

https://github.com/clbarnes/backports.strenum/blob/9cb063cdc2d2e94229e7fc66c9a989379e1bff68/LICENSE

Since this is a backport, I'm guessing the PSF license is correct. Could you please correct this?

**Comment by clbarnes** [comment]
You're correct, over-eager with my project templating. Happy to merge a PR immediately, might be a bit longer before I can make the change myself.

**Comment by jakirkham** [comment]
Looks like there is a fix in PR: https://github.com/clbarnes/backports.strenum/pull/13
