### ISSUE TITLE
Code has been updated in cpython.

### ISSUE THREAD

**Issue by irgeek** [clbarnes/backports.strenum#2]
I just noticed that your back-ported code is out-of-sync with the `cpython` source. Amongst other changes, a `_generate_next_value_` method has been added for compatibility with `auto`:

https://github.com/python/cpython/blob/7aaeb2a3d682ecba125c33511e4b4796021d2f82/Lib/enum.py#L1046-L1050

**Comment by clbarnes** [comment]
Thanks for letting me know! I remember that being something missing in the stdlib compared to your impl. I'll get to it soon!

**Comment by clbarnes** [comment]
I think this is resolved and I just forgot to close the issue.
