### ISSUE TITLE
New release from master branch

### ISSUE THREAD

**Issue by simonschmidt** [clbarnes/backports.strenum#7]
Hi!

We're currently pinning latest master commit when we install backports.strenum to get the type annotation changes.

Would be great to get it as part of a regular release in pypi

Cheers!

**Comment by clbarnes** [comment]
Took a few tries but 1.2.4 is now up! https://pypi.org/project/backports.strenum/1.2.4/

**Comment by simonschmidt** [comment]
That was quick, thank you!
