### ISSUE TITLE
Is it possible for this backports to support more Python version?

### ISSUE THREAD

**Issue by luochen1990** [clbarnes/backports.strenum#8]
I noticed that the readme tells this supports `Python >=3.8.6`, but I cannot image the reason why we cannot support more version? like `>= 3.6`,  is there any special reason?

**Comment by clbarnes** [comment]
There are small changes in how classes and/or enums work in those versions (including in patch releases!) which means that tests fail one way or another. The basic functionality is the same but there are some corner cases which cause problems.

Python 3.7 is end of life in a week's time; 3.6 has been EOL for nearly 1.5 years. 3.8.6 has been out nearly 3 years and anyone using 3.8 should be on at least that patch version. I don't intend for this package to become a crutch to allow development of code for EOL python versions - rather, it's intended to allow developers stuck on older (but alive) versions to prepare for migration to modern python by incorporating modern patterns.
