### ISSUE TITLE
Not uploading a wheel and using `setuptools_scm` to define the version leads to weird results

### ISSUE THREAD

**Issue by mattatark** [clbarnes/backports.strenum#9]
Uploading a wheel in addition to the source distribution would be a good idea, and should be minimal effort since this is a pure Python package. One downside to having users always installing from source is that using `setuptools_scm` results in some weird behaviors in some versions of pip.

How to reproduce this error:
- pip version 23.1.2 (23.2.1 doesn't have this issue likely due to how it gets package metadata).
- Run `SETUPTOOLS_SCM_PRETEND_VERSION=1.0 pip install backports-strenum` and you'll see that all versions are being thrown out because of a mismatch between the expected version and the one found in the metadata

You might ask why someone would do that? Well, I was planning to use this package as a dependency for [my own](https://github.com/matteosox/pysparkplug), fixing an issue with my naive implementation of StrEnum based on the standard docs. I have a test environment where I install the package without access to git, so to get that to work, I override the version using the environment variable above. This breaks installation, and is pretty common for developers in CI/CD for example.

Hope this is helpful!

**Comment by clbarnes** [comment]
Yes, setuptools_scm can be a bit of a pain in edge cases like that (and docker); I'm moving towards poetry for most of my projects, having been spoiled by cargo.

I hadn't realise the source distribution still relied on git - I assumed that at build time of the source distribution, setuptools_scm would just write the version somewhere and call it a day. But of course, the build system itself has setuptools_scm as a dependency, which presumably looks for git as a matter of course.

Thanks for bringing this up! I'll have a look into it.

**Comment by twizmwazin** [comment]
Does this issue need help to get fixed soon? I would like to use this package but due to the version mismatch between the package name and the setuptools_scm result (0.0.0), our CI is failing with it included. I can make a PR refactoring it to not use setuptools_scm.

Edit: if poetry is your preferred tool and can fix this, I'm willing to give that one a shot.

**Comment by mattatark** [comment]
> Does this issue need help to get fixed soon? I would like to use this package but due to the version mismatch between the package name and the setuptools_scm result (0.0.0), our CI is failing with it included. I can make a PR refactoring it to not use setuptools_scm.

I think all you'd need to do is upload wheels for the relevant versions and/or a new release, and that would do the trick. Many, many packages use `setuptools_scm`, so that's quite unlikely to be the issue.

**Comment by twizmwazin** [comment]
That's true, but also not having a working sdist seems not great. I'm not sure if that's a flaw in setuptools_scm or if there is an official workaround that enables a usable sdist without scm files.

**Comment by clbarnes** [comment]
I've released a new version (well, a few, because that's always the way when trying to fix publishing workflows :sweat_smile: ) with the same code, but with both a sdist and wheel but no setuptools_scm (using poetry now). Let me know if this works for you! Sorry it took so long to get to.

**Comment by clbarnes** [comment]
I now do upload a wheel and don't depend on scm, so I think this is addressed.
